CREATE TABLE IF NOT EXISTS language (
    language_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS actor (
    actor_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(45) NOT NULL,
    last_name VARCHAR(45) NOT NULL,
    last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS category (
    category_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(25) NOT NULL,
    last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS film (
    film_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description CLOB,
    release_year SMALLINT,
    language_id SMALLINT NOT NULL,
    original_language_id SMALLINT,
    rental_duration SMALLINT NOT NULL DEFAULT 3,
    rental_rate DECIMAL(4,2) NOT NULL DEFAULT 4.99,
    length SMALLINT,
    replacement_cost DECIMAL(5,2) NOT NULL DEFAULT 19.99,
    rating VARCHAR(5) DEFAULT 'G',
    special_features VARCHAR(255),
    last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_film_language FOREIGN KEY (language_id) REFERENCES language(language_id),
    CONSTRAINT fk_film_original_language FOREIGN KEY (original_language_id) REFERENCES language(language_id)
);

CREATE TABLE IF NOT EXISTS film_actor (
    film_id SMALLINT NOT NULL,
    actor_id SMALLINT NOT NULL,
    last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (film_id, actor_id),
    CONSTRAINT fk_film_actor_film FOREIGN KEY (film_id) REFERENCES film(film_id) ON DELETE CASCADE,
    CONSTRAINT fk_film_actor_actor FOREIGN KEY (actor_id) REFERENCES actor(actor_id)
);

CREATE TABLE IF NOT EXISTS film_category (
    film_id SMALLINT NOT NULL,
    category_id SMALLINT NOT NULL,
    last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (film_id, category_id),
    CONSTRAINT fk_film_category_film FOREIGN KEY (film_id) REFERENCES film(film_id) ON DELETE CASCADE,
    CONSTRAINT fk_film_category_category FOREIGN KEY (category_id) REFERENCES category(category_id)
);

CREATE TABLE IF NOT EXISTS film_text (
    film_id SMALLINT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description CLOB,
    CONSTRAINT fk_film_text_film FOREIGN KEY (film_id) REFERENCES film(film_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_film_language_id ON film(language_id);
CREATE INDEX IF NOT EXISTS idx_film_original_language_id ON film(original_language_id);
CREATE INDEX IF NOT EXISTS idx_film_actor_actor_id ON film_actor(actor_id);
CREATE INDEX IF NOT EXISTS idx_film_category_category_id ON film_category(category_id);

