spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.MySQLDialect}
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true


